title: "Constituci칩n Mexicana"
description: "Repositorio interactivo para an치lisis y visualizaci칩n de la Constituci칩n Mexicana"
theme: minima
baseurl: "/<repositorio>"  # Solo si no es tu sitio principal
url: "https://c4lup0sec.github.io"
